version: '3.8'

services:
  mariadb:
    container_name: hsa1016-mariadb
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      - MARIADB_DATABASE=hsa1016
      - MARIADB_USER=hsa1016
      - MARIADB_PASSWORD=cfltcznmiscnyflwznm0
      - MARIADB_RANDOM_ROOT_PASSWORD=true
    volumes:
      - hsa1016-maria-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - hsa1016

  elasticsearch:
    container_name: hsa1016-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    volumes:
      - hsa1016-elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - MEM_LIMIT=1073741824
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
    ports:
      - 9200:9200
    networks:
      - hsa1016
    depends_on:
      - mariadb

  kibana:
    container_name: hsa1016-kibana
    image: docker.elastic.co/kibana/kibana:8.10.2
    environment:
      - ELASTICSEARCH_HOSTS=http://hsa1016-elasticsearch:9200
    networks:
      - hsa1016
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  logstash:
    container_name: hsa1016-logstash
    image: logstash:8.11.1
    environment:
      - xpack.monitoring.enabled=false
      - ELASTICSEARCH_HOSTS=http://hsa1016-elasticsearch:9200
    volumes:
      - ./logstash/pipeline.yml:/usr/share/logstash/config/pipeline.yml
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    ports:
      - 5044:5044
    networks:
      - hsa1016
    depends_on:
      - mariadb
      - elasticsearch
    
networks:
  hsa1016:
    name: hsa1016

volumes:
  hsa1016-elasticsearch-data:
    driver: local
  hsa1016-maria-data:
    driver: local